"""raid events

Revision ID: 17e49d664826
Revises: b1a5e35a0ac3
Create Date: 2026-08-16 14:06:56.566835
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '17e49d664826'
down_revision: str | None = 'b1a5e35a0ac3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raid_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('join_count', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raid_events_chat', 'raid_events', ['chat_telegram_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raid_events_chat', table_name='raid_events')
    op.drop_table('raid_events')
    # ### end Alembic commands ###
