"""initial schema

Revision ID: 1b9c903a62a1
Revises: 
Create Date: 2026-08-16 13:12:23.443678
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1b9c903a62a1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_verdicts_chat_telegram_id'), 'ai_verdicts', ['chat_telegram_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_telegram_id'), 'chats', ['telegram_id'], unique=True)
    op.create_table('mod_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_modactions_chat', 'mod_actions', ['chat_telegram_id', 'created_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_chat_telegram_id'), 'subscriptions', ['chat_telegram_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('warns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('issued_by', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warns_chat_user', 'warns', ['chat_telegram_id', 'user_telegram_id'], unique=False)
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('warn_limit', sa.Integer(), nullable=False),
    sa.Column('warn_action', sa.String(length=16), nullable=False),
    sa.Column('ai_mode', sa.String(length=16), nullable=False),
    sa.Column('ai_threshold', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_settings')
    op.drop_index('ix_warns_chat_user', table_name='warns')
    op.drop_table('warns')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_chat_telegram_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_modactions_chat', table_name='mod_actions')
    op.drop_table('mod_actions')
    op.drop_index(op.f('ix_chats_telegram_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_ai_verdicts_chat_telegram_id'), table_name='ai_verdicts')
    op.drop_table('ai_verdicts')
    # ### end Alembic commands ###
