"""Add ChatTrigger and GlobalBan

Revision ID: 1cdedb550111
Revises: 1cdeda440995
Create Date: 2026-09-13 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cdedb550111'
down_revision: Union[str, None] = '1cdeda440995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_word', sa.String(length=255), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('is_regex', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_triggers_chat', 'chat_triggers', ['chat_telegram_id'], unique=False)
    
    op.create_table('global_bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_global_bans_admin', 'global_bans', ['admin_telegram_id', 'user_telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_global_bans_admin', table_name='global_bans')
    op.drop_table('global_bans')
    op.drop_index('ix_chat_triggers_chat', table_name='chat_triggers')
    op.drop_table('chat_triggers')
    # ### end Alembic commands ###
