"""bot registry + chat bot_id

Revision ID: 70b60a66531c
Revises: d0ae6735c690
Create Date: 2026-08-17 04:41:12.519264
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '70b60a66531c'
down_revision: str | None = 'd0ae6735c690'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_instances_bot_telegram_id'), 'bot_instances', ['bot_telegram_id'], unique=True)
    op.add_column('chats', sa.Column('bot_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_chats_bot_id'), 'chats', ['bot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_bot_id'), table_name='chats')
    op.drop_column('chats', 'bot_id')
    op.drop_index(op.f('ix_bot_instances_bot_telegram_id'), table_name='bot_instances')
    op.drop_table('bot_instances')
    # ### end Alembic commands ###
