"""ai verdict text

Revision ID: 8d5f75492151
Revises: 17e49d664826
Create Date: 2026-08-16 14:25:39.717977
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8d5f75492151'
down_revision: str | None = '17e49d664826'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_verdicts', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_verdicts', 'text')
    # ### end Alembic commands ###
