"""payments ledger

Revision ID: afcccc433ed9
Revises: 8d5f75492151
Create Date: 2026-08-17 02:45:36.194812
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'afcccc433ed9'
down_revision: str | None = '8d5f75492151'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('payer_id', sa.BigInteger(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('telegram_payment_charge_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_payment_charge_id')
    )
    op.create_index('ix_payments_chat', 'payments', ['chat_telegram_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_chat', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
