"""captcha sessions

Revision ID: b1a5e35a0ac3
Revises: 1b9c903a62a1
Create Date: 2026-08-16 13:27:15.781411
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b1a5e35a0ac3'
down_revision: str | None = '1b9c903a62a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('is_join_request', sa.Boolean(), nullable=False),
    sa.Column('prompt_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_captcha_chat_user', 'captcha_sessions', ['chat_telegram_id', 'user_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_captcha_chat_user', table_name='captcha_sessions')
    op.drop_table('captcha_sessions')
    # ### end Alembic commands ###
