"""chat members roster

Revision ID: d0ae6735c690
Revises: afcccc433ed9
Create Date: 2026-08-17 04:07:49.512615
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd0ae6735c690'
down_revision: str | None = 'afcccc433ed9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_telegram_id', 'user_telegram_id', name='uq_chat_member')
    )
    op.create_index('ix_chat_members_chat', 'chat_members', ['chat_telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_members_chat', table_name='chat_members')
    op.drop_table('chat_members')
    # ### end Alembic commands ###
